### ISSUE TITLE
./util import issue

### ISSUE THREAD

**Issue by WAvdBeek** [mulesoft/oas-raml-converter#20]
just running the tool from an cloned repo gives the following error:

converting ... ../../swagger2.0/swagger.json
module.js:472
    throw err;
    ^

Error: Cannot find module './util'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wovander\Documents\Wouter\API\ivp-vDCM\scrip
ts\oas-raml-converter\lib\bin\converter.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

this happens when running from:
lib/bin/converter.js
when running from
src/bin/converter.js
the next error occurs:

$ sh convert_swagger.sh
converting ... ../../swagger2.0/swagger.json
C:\Users\wovander\Documents\Wouter\API\ivp-vDCM\scripts\oas-raml-converter\src\r
aml10\raml10Converter.js:39
        _loadFile(filePath:string, options:any) {
                          ^
SyntaxError: Unexpected token :
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\wovander\Documents\Wouter\API\ivp-vDCM\scrip
ts\oas-raml-converter\src\converters\index.js:2:8)

**Comment by glodieu** [comment]
README updated. Please try again. Thanks!
