### ISSUE TITLE
Running oas-raml-converter throws an error

### ISSUE THREAD

**Issue by hotgazpacho** [mulesoft/oas-raml-converter#26]
oas-raml-converter is installed globally. However, when I run it, it immediately raises an error:

```
> oas-raml-converter
module.js:471
    throw err;
    ^

Error: Cannot find module 'serializer.ts/Decorators'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wgreen/.nvm/versions/node/v6.10.3/lib/node_modules/oas-raml-converter/node_modules/oas-raml-converter-model/lib/model/index.js:12:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
```

Node version is 6.10.3
NPM version is 3.10.10

**Comment by defel** [comment]
same problem with node v7.3.0

**Comment by Pradeepraj** [comment]
npm install serializer.ts

This should solve the issue.
